version: '3.9'

networks:
  rinha-network:
    driver: bridge
  payment-processor-network:
    external: true
    name: payment-processor

services:
  nginx:
    image: nginx:1.25.2-alpine
    ports:
      - "9999:9999"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - rinha-network
    depends_on:
      - backend-1
      - backend-2
    deploy:
      resources:
        limits:
          cpus: "0.10"
          memory: "25MB"

  redis:
    image: redis:7.2-alpine
    networks:
      - rinha-network
    deploy:
      resources:
        limits:
          cpus: "0.20"
          memory: "50MB"

  backend-1:
    build: .
    hostname: backend-1
    networks:
      - rinha-network
      - payment-processor-network
    depends_on:
      - redis
    deploy:
      resources:
        limits:
          cpus: "0.60"
          memory: "137MB"
    environment:
       - Redis__ConnectionString=redis:6379
       - PaymentProcessorUri__Default=http://payment-processor-default:8080
       - PaymentProcessorUri__Fallback=http://payment-processor-fallback:8080

  backend-2:
    build: .
    hostname: backend-2
    networks:
      - rinha-network
      - payment-processor-network
    depends_on:
      - redis
    deploy:
      resources:
        limits:
          cpus: "0.60"
          memory: "138MB"
    environment:
       - Redis__ConnectionString=redis:6379
       - PaymentProcessorUri__Default=http://payment-processor-default:8080
       - PaymentProcessorUri__Fallback=http://payment-processor-fallback:8080 
